listener 1883
allow_anonymous false
password_file /mosquitto/auth/passwd
acl_file /mosquitto/auth/acl
persistence true
persistence_location /mosquitto/data/
autosave_interval 60
max_queued_messages 10000
